apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploily-back
  name: deploily-back
  namespace: deploily
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploily-back
  strategy: {}
  template:
    metadata:
      labels:
        app: deploily-back
    spec:
      hostAliases:
        - ip: "10.96.12.205"
          hostnames:
            - "auth.deploily.local"
      containers:
        - image: ghcr.io/deploily/deploily-backend:main
          imagePullPolicy: Always
          name: deploily-back
          command:
            - /start
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: DEBUG
              value: "true"
            - name: SECRET_KEY
              value: "..."
            - name: ALLOWED_HOSTS
              value: ".localhost,127.0.0.1,[::1],deploily.local"
            - name: CSRF_TRUSTED_ORIGINS
              value: "http://localhost,http://127.0.0.1,https://deploily.local"
            - name: FLASK_APP
              value: wsgi.py
            - name: FLASK_RUN_PORT
              value: "5000"
            - name: FLASK_DEBUG
              value: ""
            - name: SQLALCHEMY_DATABASE_URI
              value: "postgresql://deploily:deploily@postgres.deploily.svc.cluster.local:5432/deploily"
            - name: APP_FOLDER
              value: app

            - name: KEYKCLOAK_URL
              value: http://auth.deploily.local
            - name: KEYCLOAK_REALM_NAME
              value: deploily
            - name: KEYCLOAK_CLIENT_SECRET
              value: 35hhrgSoqQee2pDEu7vBToejT4Y9t7uK
            - name: KEYCLOAK_CLIENT_ID
              value: deploily


            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "465"
            - name: MAIL_USER
              value: "naoufel88.chementel@gmail.com"
            - name: MAIL_PASS
              value: "brdf pgua orhc selm"
            - name: NOTIFICATION_EMAIL
              value: "naoufel88.chementel@gmail.com"
            - name: SUPPORT_EMAIL
              value: "testmailer@transformatek.dz"

            - name: CACHE_TYPE
              value: "..."

            - name: SCHEDULER_ENABLED
              value: "False"

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploily-back
  name: deploily-back
  namespace: deploily
spec:
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    app: deploily-back
  type: ClusterIP
